[package]
name = "turi"
version = "0.1.0"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2018"

[profile.release]
debug = true

[features]
default = ["crossterm-backend"]
crossterm-backend = ["crossterm"]
bench = []

[dependencies]
unicode-width = "0.1.7"
enum-map = "0.6.2"
enumset = "0.4.5"
enumset_derive = "0.4.4"
ansi_term = "0.12.1"

[dependencies.crossterm]
version = "0.16"
optional = true
