[package]
name = "turi"
version = "0.1.0"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2018"

[features]
crossterm-backend = ["crossterm"]

[dependencies]
enumflags2 = "0.6.2"
unicode-width = "0.1.7"
derive_more = "0.99.2"
log = "0.4.8"
ansi_term = "0.12.1"

[dependencies.crossterm]
version = "0.16"
optional = true

[dev-dependencies]
simplelog = "0.7.4"
log-panics = { version = "2.0.0", features = ["with-backtrace"] }
