[package]
name = "turi"
version = "0.1.0"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2018"

[profile.release]
debug = true

[features]
default = ["crossterm-backend"]
crossterm-backend = ["crossterm"]

[dependencies]
unicode-width = "0.1.7"
log = "0.4.8"
enum-map = "0.6.2"
enumset = "0.4.5"
enumset_derive = "0.4.4"

[dependencies.crossterm]
version = "0.16"
optional = true

[dev-dependencies]
simplelog = "0.7.4"
log-panics = { version = "2.0.0", features = ["with-backtrace"] }
