[package]
name = "turi"
version = "0.1.0"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2018"

[profile.release]
debug = true

[features]
default = ["crossterm-backend", "test-backend"]
crossterm-backend = ["crossterm"]
test-backend = []
bench = []

[dependencies]
unicode-width = "0.1.7"
enum-map = "0.6.2"
enumset = "0.4.5"
enumset_derive = "0.4.4"
ansi_term = "0.12.1"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
winapi = "0.3.8"

[dependencies.crossterm]
version = "0.16"
optional = true

[dev-dependencies]
pretty_assertions = "0.6.1"
log = "0.4.8"
simplelog = "0.7.4"
