indent_style = "Block"
imports_indent = "Block"
imports_layout = "Vertical"
merge_imports = true
force_multiline_blocks = true
newline_style = "Unix"
reorder_impl_items = true
fn_args_layout = "Vertical"
use_field_init_shorthand = true
use_try_shorthand = true
overflow_delimited_expr = true
max_width = 100
struct_field_align_threshold = 25